/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AlertSeverity } from './alert-severity';

/**
 * Payload for updating an existing clinical alert rule with partial attributes.  Attributes:     unit_category (str | None): Updated unit or department category.     threshold_percentage (float | None): Updated trigger percentage.     severity (AlertSeverity | None): Updated severity classification.     is_active (bool | None): Updated active evaluation flag.
 */
export interface AlertRuleUpdate {
  unit_category?: string | null;
  threshold_percentage?: number | null;
  severity?: AlertSeverity | null;
  is_active?: boolean | null;
}
export namespace AlertRuleUpdate {}
