/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AlertSeverity } from './alert-severity';

/**
 * Payload for creating a new clinical alert rule.
 */
export interface AlertRuleCreate {
  /**
   * Unit or department category
   */
  unit_category: string;
  /**
   * Trigger occupancy percentage
   */
  threshold_percentage: number;
  /**
   * Alert severity level
   */
  severity?: AlertSeverity;
  /**
   * Active status flag
   */
  is_active?: boolean;
}
export namespace AlertRuleCreate {}
