/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Real-time hospital unit capacity alert payload.
 */
export interface BedCapacityAlert {
  unit_category: string;
  current_census: number;
  max_capacity: number;
  occupancy_percentage: number;
  threshold_percentage: number;
  severity: BedCapacityAlert.SeverityEnum;
  message: string;
  timestamp: string;
}
export namespace BedCapacityAlert {
  export const SeverityEnum = {
    Info: 'INFO',
    Warning: 'WARNING',
    Critical: 'CRITICAL',
  } as const;
  export type SeverityEnum = (typeof SeverityEnum)[keyof typeof SeverityEnum];
}
