/* v8 ignore start */
/** @docs */
/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * API Response model for a Conversation metadata wrapper.
 */
export interface ConversationResponse {
  title?: string | null;
  id: string;
  user_id: string;
  created_at: string;
  updated_at: string;
}
