/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageResponse } from './message-response';

/**
 * Detailed view including message history.
 */
export interface ConversationDetail {
  title?: string | null;
  id: string;
  user_id: string;
  created_at: string;
  updated_at: string;
  messages?: Array<MessageResponse>;
}
