/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WidgetResponse } from './widget-response';

/**
 * API Response model for a Dashboard. Includes the nested list of Widgets and permission level.
 */
export interface DashboardResponse {
  name: string;
  id: string;
  owner_id: string;
  permission_level?: string;
  widgets?: Array<WidgetResponse>;
}
