/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Payload for sharing a dashboard with another user by email.
 */
export interface DashboardShareCreate {
  user_email: string;
  permission_level?: string;
}
