/**
 * Hospital Analytics Platform
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WidgetResponse } from './widget-response';


export interface DashboardResponse { 
    name: string;
    id: string;
    owner_id: string;
    widgets?: Array<WidgetResponse>;
}

