/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Schema for DuckDB analytics engine status.
 */
export interface DuckDbHealthSchema {
  /**
   * Storage and query engine status (e.g. ready, error).
   */
  status: string;
  path?: string | null;
  /**
   * Map of table names to row counts.
   */
  tables?: { [key: string]: number };
  /**
   * Total number of registered analytics tables.
   */
  total_tables?: number;
  error?: string | null;
}
