/* v8 ignore start */
/** @docs */
/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * DTO for a single Arena Candidate.
 */
export interface MessageCandidateResponse {
  id: string;
  model_name: string;
  content: string;
  sql_snippet?: string | null;
  sql_hash?: string | null;
  is_selected: boolean;
}
