/* v8 ignore start */
/** @docs */
/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Payload for voting on a candidate.
 */
export interface MessageVoteRequest {
  candidate_id: string;
}
