/* v8 ignore start */
/** @docs */
/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageCandidateResponse } from './message-candidate-response';

/**
 * API Response model for a persisted Message.
 */
export interface MessageResponse {
  content: string;
  id: string;
  conversation_id: string;
  role: string;
  sql_snippet?: string | null;
  created_at: string;
  candidates?: Array<MessageCandidateResponse>;
}
