/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MpaxArenaCandidate } from './mpax-arena-candidate';

/**
 * Response returned after executing an MPAX Arena scenario.
 */
export interface MpaxArenaResponse {
  experiment_id: string;
  mode: string;
  ground_truth_mpax?: Record<string, any> | null;
  candidates: Array<MpaxArenaCandidate>;
}
