/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Status confirmation after password reset or email dispatch.
 */
export interface PasswordResetResponse {
  message: string;
  reset_token?: string | null;
}
