/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Single row in the optimization result.
 */
export interface SimulationAssignment {
  Service: string;
  Unit: string;
  Patient_Count: number;
  /**
   * Count in this unit before optimization (if provided).
   */
  Original_Count?: number;
  /**
   * Net change (Proposed - Original).
   */
  Delta?: number;
}
