/* v8 ignore start */
/** @docs */
/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response model containing SQL execution results.
 */
export interface SQLExecutionResponse {
  data: Array<{ [key: string]: any }>;
  columns: Array<string>;
  error?: string | null;
}
