/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request model for executing SQL and returning a preview result.
 */
export interface SQLExecutionRequest {
  sql: string;
  max_rows?: number | null;
  global_params?: { [key: string]: any };
}
