/* v8 ignore start */
/** @docs */
/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Configuration schema for SQL-type widgets. Enforces the presence of a SQL query string.  Attributes:     query (str): The raw SQL query to execute.     xKey (Optional[str]): Column name to mapping for X-Axis/Labels.     yKey (Optional[str]): Column name to mapping for Y-Axis/Values.
 */
export interface SqlConfig {
  /**
   * Grid X position
   */
  x?: number;
  /**
   * Grid Y position
   */
  y?: number;
  /**
   * Grid Width (cols)
   */
  w?: number;
  /**
   * Grid Height (rows)
   */
  h?: number;
  /**
   * The raw SQL query to execute.
   */
  query: string;
  xKey?: string | null;
  yKey?: string | null;
}
