/**
 * Hospital Analytics Platform
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * API Response model for a Template. Include database ID.
 */
export interface TemplateResponse { 
    title: string;
    description?: string | null;
    /**
     * SQL with {{handlebars}} placeholders
     */
    sql_template: string;
    category: string;
    /**
     * JSON Schema definition for dynamic form generation.
     */
    parameters_schema?: { [key: string]: any; };
    id: string;
}

