/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Configuration schema for Static Text/Markdown widgets.  Attributes:     content (str): The static text content (Markdown supported).
 */
export interface TextConfig {
  /**
   * Grid X position
   */
  x?: number;
  /**
   * Grid Y position
   */
  y?: number;
  /**
   * Grid Width (cols)
   */
  w?: number;
  /**
   * Grid Height (rows)
   */
  h?: number;
  /**
   * Markdown text content.
   */
  content: string;
}
