/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Public representation of a user returned by the API.
 */
export interface UserResponse {
  id: string;
  email: string;
  is_active: boolean;
  is_admin: boolean;
}
