/**
 * Hospital Analytics Platform
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WidgetUpdate { 
    title?: string | null;
    visualization?: string | null;
    config?: { [key: string]: any; } | null;
}

