/* v8 ignore start */
/** @docs */
/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TextConfig } from './text-config';

/**
 * Payload for creating a Text Widget. Strictly enforces `type=\"TEXT\"` and `config` matching TextConfig.
 */
export interface WidgetCreateText {
  title: string;
  type: WidgetCreateText.TypeEnum;
  /**
   * Fixed visualization ID for text.
   */
  visualization?: WidgetCreateText.VisualizationEnum;
  /**
   * Text-specific configuration
   */
  config: TextConfig;
}
export namespace WidgetCreateText {
  /** @docs */
  export const TypeEnum = {
    Text: 'TEXT',
  } as const;
  /** @docs */
  export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];
  /** @docs */
  export const VisualizationEnum = {
    Markdown: 'markdown',
  } as const;
  /** @docs */
  export type VisualizationEnum = (typeof VisualizationEnum)[keyof typeof VisualizationEnum];
}
