/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WidgetReorderItem } from './widget-reorder-item';

/**
 * Bulk update payload for persisting drag-and-drop results.
 */
export interface WidgetReorderRequest {
  items: Array<WidgetReorderItem>;
}
