/**
 * Hospital Analytics Platform
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WidgetCreate { 
    title: string;
    type: string;
    visualization: string;
    config: { [key: string]: any; };
}

