/**
 * Hospital Analytics Platform
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpConfig } from './http-config';


/**
 * Payload for creating an HTTP Widget. Strictly enforces `type=\"HTTP\"` and `config` matching HttpConfig.
 */
export interface WidgetCreateHttp { 
    title: string;
    type: WidgetCreateHttp.TypeEnum;
    /**
     * Visualization ID (e.g. \'table\', \'metric\')
     */
    visualization: string;
    /**
     * HTTP-specific configuration
     */
    config: HttpConfig;
}
export namespace WidgetCreateHttp {
    export const TypeEnum = {
        Http: 'HTTP'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


