/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a single widget\'s new position.
 */
export interface WidgetReorderItem {
  id: string;
  order: number;
  group?: string | null;
}
