/* v8 ignore start */
/** @docs */
/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * API Response model for a persisted Widget.
 */
export interface WidgetResponse {
  title: string;
  type: string;
  visualization: string;
  config: { [key: string]: any };
  id: string;
  dashboard_id: string;
}
