/* v8 ignore start */
/** @docs */
/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WidgetCreateSql } from './widget-create-sql';
import { TextConfig } from './text-config';
import { WidgetCreateHttp } from './widget-create-http';
import { WidgetCreateText } from './widget-create-text';

/**
 * @type WidgetIn
 * @export
 */
export type WidgetIn = WidgetCreateHttp | WidgetCreateSql | WidgetCreateText;
