/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a Widget configuration returned from the backend.
 */
export interface WidgetResponse {
    /** The display title of the widget. */
    title: string;
    /** The data source type (e.g., 'SQL' or 'HTTP'). */
    type: string;
    /** The ID of the visualization component to render (e.g., 'table', 'bar_chart'). */
    visualization: string;
    /**
     * Configuration dictionary containing execution logic and display settings.
     *
     * JSON Schema:
     * - query (string): The SQL query to execute (Type: SQL).
     * - url (string): The endpoint URL (Type: HTTP).
     * - xKey (string): The column name to map to the X-Axis or Labels.
     * - yKey (string): The column name to map to the Y-Axis or Values.
     * - w, h, x, y (numbers): Grid layout positioning.
     */
    config: { [key: string]: any; };
    /** Unique Widget ID (UUID). */
    id: string;
    /** ID of the parent Dashboard. */
    dashboard_id: string;
}