/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { ConversationCreate } from '../model/conversation-create';
// @ts-ignore
import { ConversationResponse } from '../model/conversation-response';
// @ts-ignore
import { MessageCreate } from '../model/message-create';
// @ts-ignore
import { MessageResponse } from '../model/message-response';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';

@Injectable({
  providedIn: 'root'
})
export class ChatService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Create Conversation
     * @param conversationCreate 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public createConversationApiV1ConversationsPost(conversationCreate: ConversationCreate, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ConversationResponse>;
    public createConversationApiV1ConversationsPost(conversationCreate: ConversationCreate, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ConversationResponse>>;
    public createConversationApiV1ConversationsPost(conversationCreate: ConversationCreate, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ConversationResponse>>;
    public createConversationApiV1ConversationsPost(conversationCreate: ConversationCreate, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        let localVarHeaders = this.defaultHeaders;
        let localVarPath = `/api/v1/conversations/`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ConversationResponse>('post', `${basePath}${localVarPath}`,
            {
                body: conversationCreate,
                headers: localVarHeaders,
                observe: observe,
                responseType: 'json',
                ...(withCredentials ? { withCredentials } : {})
            }
        );
    }

    /**
     * Get Messages
     * @param conversationId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getMessagesApiV1ConversationsConversationIdMessagesGet(conversationId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<MessageResponse>>;
    public getMessagesApiV1ConversationsConversationIdMessagesGet(conversationId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<MessageResponse>>>;
    public getMessagesApiV1ConversationsConversationIdMessagesGet(conversationId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<MessageResponse>>>;
    public getMessagesApiV1ConversationsConversationIdMessagesGet(conversationId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        let localVarHeaders = this.defaultHeaders;
        let localVarPath = `/api/v1/conversations/${encodeURIComponent(String(conversationId))}/messages`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<MessageResponse>>('get', `${basePath}${localVarPath}`,
            {
                headers: localVarHeaders,
                observe: observe,
                responseType: 'json',
                ...(withCredentials ? { withCredentials } : {})
            }
        );
    }

    /**
     * List Conversations
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public listConversationsApiV1ConversationsGet(observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<ConversationResponse>>;
    public listConversationsApiV1ConversationsGet(observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<ConversationResponse>>>;
    public listConversationsApiV1ConversationsGet(observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<ConversationResponse>>>;
    public listConversationsApiV1ConversationsGet(observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        let localVarHeaders = this.defaultHeaders;
        let localVarPath = `/api/v1/conversations/`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<ConversationResponse>>('get', `${basePath}${localVarPath}`,
            {
                headers: localVarHeaders,
                observe: observe,
                responseType: 'json',
                ...(withCredentials ? { withCredentials } : {})
            }
        );
    }

    /**
     * Send Message
     * @param conversationId 
     * @param messageCreate 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public sendMessageApiV1ConversationsConversationIdMessagesPost(conversationId: string, messageCreate: MessageCreate, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<MessageResponse>;
    public sendMessageApiV1ConversationsConversationIdMessagesPost(conversationId: string, messageCreate: MessageCreate, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<MessageResponse>>;
    public sendMessageApiV1ConversationsConversationIdMessagesPost(conversationId: string, messageCreate: MessageCreate, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<MessageResponse>>;
    public sendMessageApiV1ConversationsConversationIdMessagesPost(conversationId: string, messageCreate: MessageCreate, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        let localVarHeaders = this.defaultHeaders;
        let localVarPath = `/api/v1/conversations/${encodeURIComponent(String(conversationId))}/messages`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<MessageResponse>('post', `${basePath}${localVarPath}`,
            {
                body: messageCreate,
                headers: localVarHeaders,
                observe: observe,
                responseType: 'json',
                ...(withCredentials ? { withCredentials } : {})
            }
        );
    }

}