/** 
 * Hospital Analytics Platform
 * 
 * 
 * 
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). 
 * https://openapi-generator.tech
 * Do not edit the class manually. 
 */ 
/* tslint:disable:no-unused-variable member-ordering */ 

import { Inject, Injectable, Optional }                      from '@angular/core'; 
import { HttpClient, HttpHeaders, HttpParams, 
         HttpResponse, HttpEvent, HttpContext
        }       from '@angular/common/http'; 
import { Observable }                                        from 'rxjs'; 
import { OpenApiHttpParams, QueryParamStyle } from '../query.params'; 

// @ts-ignore
import { ConversationCreate } from '../model/conversation-create'; 
// @ts-ignore
import { ConversationUpdate } from '../model/conversation-update'; 
// @ts-ignore
import { ConversationResponse } from '../model/conversation-response'; 
// @ts-ignore
import { MessageCreate } from '../model/message-create'; 
// @ts-ignore
import { MessageResponse } from '../model/message-response'; 
// @ts-ignore
import { MessageVoteRequest } from '../model/message-vote'; 

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables'; 
import { Configuration }                                     from '../configuration'; 
import { BaseService } from '../api.base.service'; 

@Injectable({ 
  providedIn: 'root' 
}) 
export class ChatService extends BaseService { 

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) { 
        super(basePath, configuration); 
    } 

    /** 
     * Create Conversation
     * @endpoint post /api/v1/conversations/ 
     */ 
    public createConversationApiV1ConversationsPost(conversationCreate: ConversationCreate, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> { 
        let localVarHeaders = this.defaultHeaders; 
        let localVarPath = `/api/v1/conversations/`; 
        const { basePath, withCredentials } = this.configuration; 
        return this.httpClient.request<ConversationResponse>('post', `${basePath}${localVarPath}`, 
            { 
                body: conversationCreate, 
                headers: localVarHeaders, 
                observe: observe, 
                responseType: 'json', 
                ...(withCredentials ? { withCredentials } : {}) 
            } 
        ); 
    } 

    /** 
     * Update Conversation (Rename) 
     * @endpoint put /api/v1/conversations/{conversation_id} 
     */ 
    public updateConversationApiV1ConversationsConversationIdPut(conversationId: string, conversationUpdate: ConversationUpdate, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> { 
        let localVarHeaders = this.defaultHeaders; 
        let localVarPath = `/api/v1/conversations/${encodeURIComponent(String(conversationId))}`; 
        const { basePath, withCredentials } = this.configuration; 
        return this.httpClient.request<ConversationResponse>('put', `${basePath}${localVarPath}`, 
            { 
                body: conversationUpdate, 
                headers: localVarHeaders, 
                observe: observe, 
                responseType: 'json', 
                ...(withCredentials ? { withCredentials } : {}) 
            } 
        ); 
    } 

    /** 
     * Delete Conversation
     * @endpoint delete /api/v1/conversations/{conversation_id} 
     */ 
    public deleteConversationApiV1ConversationsConversationIdDelete(conversationId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> { 
        let localVarHeaders = this.defaultHeaders; 
        let localVarPath = `/api/v1/conversations/${encodeURIComponent(String(conversationId))}`; 
        const { basePath, withCredentials } = this.configuration; 
        return this.httpClient.request<any>('delete', `${basePath}${localVarPath}`, 
            { 
                headers: localVarHeaders, 
                observe: observe, 
                responseType: 'json', 
                ...(withCredentials ? { withCredentials } : {}) 
            } 
        ); 
    } 

    public getMessagesApiV1ConversationsConversationIdMessagesGet(conversationId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> { 
        let localVarHeaders = this.defaultHeaders; 
        let localVarPath = `/api/v1/conversations/${encodeURIComponent(String(conversationId))}/messages`; 
        const { basePath, withCredentials } = this.configuration; 
        return this.httpClient.request<Array<MessageResponse>>('get', `${basePath}${localVarPath}`, 
            { 
                headers: localVarHeaders, 
                observe: observe, 
                responseType: 'json', 
                ...(withCredentials ? { withCredentials } : {}) 
            } 
        ); 
    } 

    public listConversationsApiV1ConversationsGet(observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> { 
        let localVarHeaders = this.defaultHeaders; 
        let localVarPath = `/api/v1/conversations/`; 
        const { basePath, withCredentials } = this.configuration; 
        return this.httpClient.request<Array<ConversationResponse>>('get', `${basePath}${localVarPath}`, 
            { 
                headers: localVarHeaders, 
                observe: observe, 
                responseType: 'json', 
                ...(withCredentials ? { withCredentials } : {}) 
            } 
        ); 
    } 

    public sendMessageApiV1ConversationsConversationIdMessagesPost(conversationId: string, messageCreate: MessageCreate, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> { 
        let localVarHeaders = this.defaultHeaders; 
        let localVarPath = `/api/v1/conversations/${encodeURIComponent(String(conversationId))}/messages`; 
        const { basePath, withCredentials } = this.configuration; 
        return this.httpClient.request<MessageResponse>('post', `${basePath}${localVarPath}`, 
            { 
                body: messageCreate, 
                headers: localVarHeaders, 
                observe: observe, 
                responseType: 'json', 
                ...(withCredentials ? { withCredentials } : {}) 
            } 
        ); 
    } 

    public voteMessageApiV1ConversationsConversationIdMessagesMessageIdVotePost(conversationId: string, messageId: string, messageVoteRequest: MessageVoteRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> { 
        let localVarHeaders = this.defaultHeaders; 
        let localVarPath = `/api/v1/conversations/${encodeURIComponent(String(conversationId))}/messages/${encodeURIComponent(String(messageId))}/vote`; 
        const { basePath, withCredentials } = this.configuration; 
        return this.httpClient.request<MessageResponse>('post', `${basePath}${localVarPath}`, 
            { 
                body: messageVoteRequest, 
                headers: localVarHeaders, 
                observe: observe, 
                responseType: 'json', 
                ...(withCredentials ? { withCredentials } : {}) 
            } 
        ); 
    } 
}