/**
 * Hospital Analytics Platform
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent, HttpContext } from '@angular/common/http';
import { Observable } from 'rxjs';

// Models
import { DashboardCreate } from '../model/dashboard-create';
import { DashboardResponse } from '../model/dashboard-response';
import { WidgetCreate } from '../model/widget-create';
import { WidgetResponse } from '../model/widget-response';
import { WidgetUpdate } from '../model/widget-update';

// Base
import { BASE_PATH } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';

/**
 * Service for managing Dashboard operations (CRUD).
 */
@Injectable({
  providedIn: 'root'
})
export class DashboardsService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Create Dashboard
     * Create a new empty dashboard.
     * @param dashboardCreate Dashboard Creation Payload
     * @param observe Response Type ('body', 'response', 'events')
     */
    public createDashboardApiV1DashboardsPost(dashboardCreate: DashboardCreate, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
        if (dashboardCreate === null || dashboardCreate === undefined) {
            throw new Error('Required parameter dashboardCreate was null or undefined when calling createDashboardApiV1DashboardsPost.');
        }

        let localVarHeaders = this.defaultHeaders;
        localVarHeaders = this.configuration.addCredentialToHeaders('OAuth2PasswordBearer', 'Authorization', localVarHeaders, 'Bearer ');

        return this.httpClient.request<DashboardResponse>('post', `${this.configuration.basePath}/api/v1/dashboards/`,
            {
                body: dashboardCreate,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create Widget
     * Add a widget to the dashboard.
     * @param dashboardId UUID of the dashboard
     * @param widgetCreate Widget Creation Payload
     */
    public createWidgetApiV1DashboardsDashboardIdWidgetsPost(dashboardId: string, widgetCreate: WidgetCreate, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
        if (!dashboardId || !widgetCreate) throw new Error('Missing required params');

        let localVarHeaders = this.defaultHeaders;
        localVarHeaders = this.configuration.addCredentialToHeaders('OAuth2PasswordBearer', 'Authorization', localVarHeaders, 'Bearer ');

        return this.httpClient.request<WidgetResponse>('post', `${this.configuration.basePath}/api/v1/dashboards/${dashboardId}/widgets`,
            {
                body: widgetCreate,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete Dashboard
     * Permanently remove a dashboard and all its widgets.
     * @param dashboardId UUID of the dashboard
     */
    public deleteDashboardApiV1DashboardsDashboardIdDelete(dashboardId: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
        if (!dashboardId) throw new Error('Missing dashboardId');

        let localVarHeaders = this.defaultHeaders;
        localVarHeaders = this.configuration.addCredentialToHeaders('OAuth2PasswordBearer', 'Authorization', localVarHeaders, 'Bearer ');

        return this.httpClient.request<any>('delete', `${this.configuration.basePath}/api/v1/dashboards/${dashboardId}`,
            {
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete Widget
     * @param widgetId UUID of the widget
     */
    public deleteWidgetApiV1DashboardsWidgetsWidgetIdDelete(widgetId: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
        if (!widgetId) throw new Error('Missing widgetId');

        let localVarHeaders = this.defaultHeaders;
        localVarHeaders = this.configuration.addCredentialToHeaders('OAuth2PasswordBearer', 'Authorization', localVarHeaders, 'Bearer ');

        return this.httpClient.request<any>('delete', `${this.configuration.basePath}/api/v1/dashboards/widgets/${widgetId}`,
            {
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Dashboard
     * Fetch full dashboard details.
     * @param dashboardId UUID
     */
    public getDashboardApiV1DashboardsDashboardIdGet(dashboardId: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
        if (!dashboardId) throw new Error('Missing dashboardId');

        let localVarHeaders = this.defaultHeaders;
        localVarHeaders = this.configuration.addCredentialToHeaders('OAuth2PasswordBearer', 'Authorization', localVarHeaders, 'Bearer ');

        return this.httpClient.request<DashboardResponse>('get', `${this.configuration.basePath}/api/v1/dashboards/${dashboardId}`,
            {
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List Dashboards
     * Fetch all dashboards for current user.
     */
    public listDashboardsApiV1DashboardsGet(observe: any = 'body', reportProgress: boolean = false): Observable<any> {
        let localVarHeaders = this.defaultHeaders;
        localVarHeaders = this.configuration.addCredentialToHeaders('OAuth2PasswordBearer', 'Authorization', localVarHeaders, 'Bearer ');

        return this.httpClient.request<Array<DashboardResponse>>('get', `${this.configuration.basePath}/api/v1/dashboards/`,
            {
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update Widget
     * @param widgetId UUID
     * @param widgetUpdate Config changes
     */
    public updateWidgetApiV1DashboardsWidgetsWidgetIdPut(widgetId: string, widgetUpdate: WidgetUpdate, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
        if (!widgetId) throw new Error('Missing widgetId');

        let localVarHeaders = this.defaultHeaders;
        localVarHeaders = this.configuration.addCredentialToHeaders('OAuth2PasswordBearer', 'Authorization', localVarHeaders, 'Bearer ');

        return this.httpClient.request<WidgetResponse>('put', `${this.configuration.basePath}/api/v1/dashboards/widgets/${widgetId}`,
            {
                body: widgetUpdate,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update Dashboard (Rename)
     * !!! NEW METHOD FOR FEATURE 06 !!!
     * 
     * @param dashboardId UUID
     * @param dashboardUpdate { name: string }
     */
    public updateDashboardApiV1DashboardsDashboardIdPut(dashboardId: string, dashboardUpdate: { name: string }, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
        if (dashboardId === null || dashboardId === undefined) {
            throw new Error('Required parameter dashboardId was null or undefined when calling updateDashboardApiV1DashboardsDashboardIdPut.');
        }

        let localVarHeaders = this.defaultHeaders;
        localVarHeaders = this.configuration.addCredentialToHeaders('OAuth2PasswordBearer', 'Authorization', localVarHeaders, 'Bearer ');

        return this.httpClient.request<DashboardResponse>('put', `${this.configuration.basePath}/api/v1/dashboards/${dashboardId}`,
            {
                body: dashboardUpdate,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }
}