services:
  db:
    image: postgres:18-alpine
    container_name: pulse-query-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pulse_query_db
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./pulse-query-backend
      dockerfile: Dockerfile
    container_name: pulse-query-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pulse_query_db
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - USE_SQLITE_ALEMBIC=1
      - DEBUG=1
    depends_on:
      - db

  frontend:
    build:
      context: ./pulse-query-ng-web
      dockerfile: Dockerfile
    container_name: pulse-query-frontend
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
