/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.apis

import io.healthplatform.pulsequery.api.models.ConversationCreate
import io.healthplatform.pulsequery.api.models.ConversationDetail
import io.healthplatform.pulsequery.api.models.ConversationResponse
import io.healthplatform.pulsequery.api.models.ConversationUpdate
import io.healthplatform.pulsequery.api.models.HTTPValidationError
import io.healthplatform.pulsequery.api.models.MessageCreate
import io.healthplatform.pulsequery.api.models.MessageResponse
import io.healthplatform.pulsequery.api.models.MessageVoteRequest

import io.healthplatform.pulsequery.api.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class ChatApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * Create Conversation
     * Create a new conversation and optionally seed the first message.
     * @param conversationCreate 
     * @return ConversationDetail
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun createConversationApiV1ConversationsPost(conversationCreate: ConversationCreate): HttpResponse<ConversationDetail> {

        val localVariableAuthNames = listOf<String>("OAuth2PasswordBearer")

        val localVariableBody = conversationCreate

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlinx.serialization.json.JsonElement?>(
            RequestMethod.POST,
            "/api/v1/conversations/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Delete Conversation
     * Delete a conversation and its messages.
     * @param conversationId 
     * @return void
     */
    open suspend fun deleteConversationApiV1ConversationsConversationIdDelete(conversationId: kotlin.String): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>("OAuth2PasswordBearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlinx.serialization.json.JsonElement?>(
            RequestMethod.DELETE,
            "/api/v1/conversations/{conversation_id}".replace("{" + "conversation_id" + "}", "$conversationId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get Messages
     * Return the ordered message history for a conversation.
     * @param conversationId 
     * @return kotlin.collections.List<MessageResponse>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getMessagesApiV1ConversationsConversationIdMessagesGet(conversationId: kotlin.String): HttpResponse<kotlin.collections.List<MessageResponse>> {

        val localVariableAuthNames = listOf<String>("OAuth2PasswordBearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlinx.serialization.json.JsonElement?>(
            RequestMethod.GET,
            "/api/v1/conversations/{conversation_id}/messages".replace("{" + "conversation_id" + "}", "$conversationId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<GetMessagesApiV1ConversationsConversationIdMessagesGetResponse>().map { value }
    }

    @Serializable(GetMessagesApiV1ConversationsConversationIdMessagesGetResponse.Companion::class)
    private class GetMessagesApiV1ConversationsConversationIdMessagesGetResponse(val value: List<MessageResponse>) {
        companion object : KSerializer<GetMessagesApiV1ConversationsConversationIdMessagesGetResponse> {
            private val serializer: KSerializer<List<MessageResponse>> = serializer<List<MessageResponse>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: GetMessagesApiV1ConversationsConversationIdMessagesGetResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = GetMessagesApiV1ConversationsConversationIdMessagesGetResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * List Conversations
     * List recent conversations for the current user.
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @return kotlin.collections.List<ConversationResponse>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun listConversationsApiV1ConversationsGet(limit: kotlin.Int? = 50, offset: kotlin.Int? = 0): HttpResponse<kotlin.collections.List<ConversationResponse>> {

        val localVariableAuthNames = listOf<String>("OAuth2PasswordBearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlinx.serialization.json.JsonElement?>(
            RequestMethod.GET,
            "/api/v1/conversations/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<ListConversationsApiV1ConversationsGetResponse>().map { value }
    }

    @Serializable(ListConversationsApiV1ConversationsGetResponse.Companion::class)
    private class ListConversationsApiV1ConversationsGetResponse(val value: List<ConversationResponse>) {
        companion object : KSerializer<ListConversationsApiV1ConversationsGetResponse> {
            private val serializer: KSerializer<List<ConversationResponse>> = serializer<List<ConversationResponse>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: ListConversationsApiV1ConversationsGetResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = ListConversationsApiV1ConversationsGetResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * Send Message
     * Append a user message and generate assistant candidates.
     * @param conversationId 
     * @param messageCreate 
     * @return MessageResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun sendMessageApiV1ConversationsConversationIdMessagesPost(conversationId: kotlin.String, messageCreate: MessageCreate): HttpResponse<MessageResponse> {

        val localVariableAuthNames = listOf<String>("OAuth2PasswordBearer")

        val localVariableBody = messageCreate

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlinx.serialization.json.JsonElement?>(
            RequestMethod.POST,
            "/api/v1/conversations/{conversation_id}/messages".replace("{" + "conversation_id" + "}", "$conversationId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Update Conversation
     * Update the title for an existing conversation.
     * @param conversationId 
     * @param conversationUpdate 
     * @return ConversationResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun updateConversationApiV1ConversationsConversationIdPut(conversationId: kotlin.String, conversationUpdate: ConversationUpdate): HttpResponse<ConversationResponse> {

        val localVariableAuthNames = listOf<String>("OAuth2PasswordBearer")

        val localVariableBody = conversationUpdate

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlinx.serialization.json.JsonElement?>(
            RequestMethod.PUT,
            "/api/v1/conversations/{conversation_id}".replace("{" + "conversation_id" + "}", "$conversationId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Vote Candidate
     * Records a user&#39;s vote for a specific generated candidate.  This selects the chosen candidate by its ID (or matching SQL hash), sets its &#x60;is_selected&#x60; flag to True, and promotes its text and SQL contents to the parent Message object.
     * @param conversationId 
     * @param messageId 
     * @param messageVoteRequest 
     * @return MessageResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun voteCandidateApiV1ConversationsConversationIdMessagesMessageIdVotePost(conversationId: kotlin.String, messageId: kotlin.String, messageVoteRequest: MessageVoteRequest): HttpResponse<MessageResponse> {

        val localVariableAuthNames = listOf<String>("OAuth2PasswordBearer")

        val localVariableBody = messageVoteRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlinx.serialization.json.JsonElement?>(
            RequestMethod.POST,
            "/api/v1/conversations/{conversation_id}/messages/{message_id}/vote".replace("{" + "conversation_id" + "}", "$conversationId").replace("{" + "message_id" + "}", "$messageId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



}
