/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param apiKeys 
 * @param visibleModels 
 */
@Serializable

data class AdminSettingsUpdateRequest (

    @SerialName(value = "api_keys") @Required val apiKeys: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @SerialName(value = "visible_models") @Required val visibleModels: kotlin.collections.List<kotlin.String>

) {


}

