/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Payload for starting a new conversation. If 'message' is provided, the conversation is initialized with it.
 *
 * @param title 
 * @param message 
 */
@Serializable

data class ConversationCreate (

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "message") val message: kotlin.String? = null

) {


}

