/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * API Response model for a Conversation metadata wrapper.
 *
 * @param id 
 * @param userId 
 * @param createdAt 
 * @param updatedAt 
 * @param title 
 */
@Serializable

data class ConversationResponse (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "user_id") @Required val userId: kotlin.String,

    @SerialName(value = "created_at") @Required val createdAt: kotlin.time.Instant,

    @SerialName(value = "updated_at") @Required val updatedAt: kotlin.time.Instant,

    @SerialName(value = "title") val title: kotlin.String? = null

) {


}

