/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Payload for sharing a dashboard with another user by email.
 *
 * @param userEmail 
 * @param permissionLevel 
 */
@Serializable

data class DashboardShareCreate (

    @SerialName(value = "user_email") @Required val userEmail: kotlin.String,

    @SerialName(value = "permission_level") val permissionLevel: kotlin.String? = "VIEW"

) {


}

