/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.models

import io.healthplatform.pulsequery.api.models.WidgetResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * API Response model for a Dashboard. Includes the nested list of Widgets.
 *
 * @param name 
 * @param id 
 * @param ownerId 
 * @param widgets 
 */
@Serializable

data class DashboardResponse (

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "owner_id") @Required val ownerId: kotlin.String,

    @SerialName(value = "widgets") val widgets: kotlin.collections.List<WidgetResponse>? = null

) {


}

