/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Configuration schema for HTTP-type widgets. Enforces the presence of a valid URL and standard HTTP properties.  Attributes:     url (HttpUrl): The fully qualified target URL.     method (str): HTTP Verb (GET, POST, etc.).     headers (Dict[str, str]): Custom request headers.     params (Dict[str, str]): URL Query parameters.     body (Optional[Any]): JSON Body for mutation requests.     meta_forward_auth (bool): If True, the backend forwards the user's JWT.     xKey (Optional[str]): key path for X-Axis/Labels.     yKey (Optional[str]): key path for Y-Axis/Values.
 *
 * @param url The fully qualified target URL.
 * @param x Grid X position
 * @param y Grid Y position
 * @param w Grid Width (cols)
 * @param h Grid Height (rows)
 * @param method HTTP Method
 * @param headers Request Headers
 * @param params Query Parameters
 * @param body JSON Body payload
 * @param metaForwardAuth If true, forwards the user's JWT to the target.
 * @param xKey 
 * @param yKey 
 */
@Serializable

data class HttpConfig (

    /* The fully qualified target URL. */
    @SerialName(value = "url") @Required val url: kotlin.String,

    /* Grid X position */
    @SerialName(value = "x") val x: kotlin.Int? = 0,

    /* Grid Y position */
    @SerialName(value = "y") val y: kotlin.Int? = 0,

    /* Grid Width (cols) */
    @SerialName(value = "w") val w: kotlin.Int? = 6,

    /* Grid Height (rows) */
    @SerialName(value = "h") val h: kotlin.Int? = 4,

    /* HTTP Method */
    @SerialName(value = "method") val method: HttpConfig.Method? = Method.GET,

    /* Request Headers */
    @SerialName(value = "headers") val headers: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* Query Parameters */
    @SerialName(value = "params") val params: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* JSON Body payload */
    @SerialName(value = "body") val body: kotlinx.serialization.json.JsonElement? = null,

    /* If true, forwards the user's JWT to the target. */
    @SerialName(value = "meta_forward_auth") val metaForwardAuth: kotlin.Boolean? = false,

    @SerialName(value = "xKey") val xKey: kotlin.String? = null,

    @SerialName(value = "yKey") val yKey: kotlin.String? = null

) {

    /**
     * HTTP Method
     *
     * Values: GET,POST,PUT,DELETE,PATCH
     */
    @Serializable
    enum class Method(val value: kotlin.String) {
        @SerialName(value = "GET") GET("GET"),
        @SerialName(value = "POST") POST("POST"),
        @SerialName(value = "PUT") PUT("PUT"),
        @SerialName(value = "DELETE") DELETE("DELETE"),
        @SerialName(value = "PATCH") PATCH("PATCH");
    }

}

