/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Schema for LLM swarm configuration and readiness.
 *
 * @param providersCount Number of configured LLM providers.
 * @param mockMode True if running in mock/fallback AI mode.
 * @param models List of active model display names.
 */
@Serializable

data class LlmHealthSchema (

    /* Number of configured LLM providers. */
    @SerialName(value = "providers_count") @Required val providersCount: kotlin.Int,

    /* True if running in mock/fallback AI mode. */
    @SerialName(value = "mock_mode") @Required val mockMode: kotlin.Boolean,

    /* List of active model display names. */
    @SerialName(value = "models") val models: kotlin.collections.List<kotlin.String>? = null

) {


}

