/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Public response schema for the frontend. Hides 'model_identifier' to maintain double-blind benchmarking.
 *
 * @param modelTag 
 * @param generatedSql 
 * @param id 
 * @param experimentId 
 * @param isSelected 
 * @param sqlHash 
 * @param latencyMs 
 */
@Serializable

data class ModelCandidateResponse (

    @SerialName(value = "model_tag") @Required val modelTag: kotlin.String,

    @SerialName(value = "generated_sql") @Required val generatedSql: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "experiment_id") @Required val experimentId: kotlin.String,

    @SerialName(value = "is_selected") @Required val isSelected: kotlin.Boolean,

    @SerialName(value = "sql_hash") val sqlHash: kotlin.String? = null,

    @SerialName(value = "latency_ms") val latencyMs: kotlin.Int? = null

) {


}

