/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.models



import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Individual LLM candidate result in an MPAX Arena experiment.
 *
 * @param id 
 * @param modelName 
 * @param content 
 * @param isSelected 
 * @param mpaxResult 
 * @param mpaxScore 
 * @param sqlSnippet 
 */
@Serializable

data class MpaxArenaCandidate (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "model_name") @Required val modelName: kotlin.String,

    @SerialName(value = "content") @Required val content: kotlin.String,

    @SerialName(value = "is_selected") val isSelected: kotlin.Boolean? = false,

    @SerialName(value = "mpax_result") val mpaxResult: kotlinx.serialization.json.JsonElement? = null,

    @SerialName(value = "mpax_score") val mpaxScore: kotlin.Int? = null,

    @SerialName(value = "sql_snippet") val sqlSnippet: kotlin.String? = null

) {


}

