/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.models


import io.healthplatform.pulsequery.api.models.MpaxArenaCandidate

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response returned after executing an MPAX Arena scenario.
 *
 * @param experimentId 
 * @param mode 
 * @param candidates 
 * @param groundTruthMpax 
 */
@Serializable

data class MpaxArenaResponse (

    @SerialName(value = "experiment_id") @Required val experimentId: kotlin.String,

    @SerialName(value = "mode") @Required val mode: kotlin.String,

    @SerialName(value = "candidates") @Required val candidates: kotlin.collections.List<MpaxArenaCandidate>,

    @SerialName(value = "ground_truth_mpax") val groundTruthMpax: kotlinx.serialization.json.JsonElement? = null

) {


}

