/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Status confirmation after password reset or email dispatch.
 *
 * @param message 
 * @param resetToken 
 */
@Serializable

data class PasswordResetResponse (

    @SerialName(value = "message") @Required val message: kotlin.String,

    @SerialName(value = "reset_token") val resetToken: kotlin.String? = null

) {


}

