/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response model containing SQL execution results.
 *
 * @param `data` 
 * @param columns 
 * @param error 
 */
@Serializable

data class SQLExecutionResponse (

    @SerialName(value = "data") @Required val `data`: kotlin.collections.List<kotlinx.serialization.json.JsonObject>,

    @SerialName(value = "columns") @Required val columns: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "error") val error: kotlin.String? = null

) {


}

