/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.models

import io.healthplatform.pulsequery.api.models.DataHealthSchema
import io.healthplatform.pulsequery.api.models.DiagnosticWarningSchema
import io.healthplatform.pulsequery.api.models.DuckDbHealthSchema
import io.healthplatform.pulsequery.api.models.LlmHealthSchema
import io.healthplatform.pulsequery.api.models.PostgresHealthSchema
import io.healthplatform.pulsequery.api.models.TemplateHealthSchema

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Schema for aggregated system health response.
 *
 * @param overallStatus Overall health status: healthy, degraded, or critical.
 * @param timestamp ISO timestamp of health assessment.
 * @param postgres Relational database health.
 * @param duckdb OLAP analytics database health.
 * @param `data` Data readiness and ingestion health.
 * @param templates Template registry health.
 * @param llm LLM provider configuration health.
 * @param warnings Active diagnostic warnings.
 */
@Serializable

data class SystemHealthResponse (

    /* Overall health status: healthy, degraded, or critical. */
    @SerialName(value = "overall_status") @Required val overallStatus: kotlin.String,

    /* ISO timestamp of health assessment. */
    @SerialName(value = "timestamp") @Required val timestamp: kotlin.String,

    /* Relational database health. */
    @SerialName(value = "postgres") @Required val postgres: PostgresHealthSchema,

    /* OLAP analytics database health. */
    @SerialName(value = "duckdb") @Required val duckdb: DuckDbHealthSchema,

    /* Data readiness and ingestion health. */
    @SerialName(value = "data") @Required val `data`: DataHealthSchema,

    /* Template registry health. */
    @SerialName(value = "templates") @Required val templates: TemplateHealthSchema,

    /* LLM provider configuration health. */
    @SerialName(value = "llm") @Required val llm: LlmHealthSchema,

    /* Active diagnostic warnings. */
    @SerialName(value = "warnings") val warnings: kotlin.collections.List<DiagnosticWarningSchema>? = null

) {


}

