/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Schema for template seeder pack health.
 *
 * @param templatesLoaded Number of widget templates seeded into database.
 * @param hasTemplates True if one or more templates are available.
 * @param missingFile True if initial_templates.json was missing.
 */
@Serializable

data class TemplateHealthSchema (

    /* Number of widget templates seeded into database. */
    @SerialName(value = "templates_loaded") @Required val templatesLoaded: kotlin.Int,

    /* True if one or more templates are available. */
    @SerialName(value = "has_templates") @Required val hasTemplates: kotlin.Boolean,

    /* True if initial_templates.json was missing. */
    @SerialName(value = "missing_file") @Required val missingFile: kotlin.Boolean

) {


}

