/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Configuration schema for Static Text/Markdown widgets.  Attributes:     content (str): The static text content (Markdown supported).
 *
 * @param content Markdown text content.
 * @param x Grid X position
 * @param y Grid Y position
 * @param w Grid Width (cols)
 * @param h Grid Height (rows)
 */
@Serializable

data class TextConfig (

    /* Markdown text content. */
    @SerialName(value = "content") @Required val content: kotlin.String,

    /* Grid X position */
    @SerialName(value = "x") val x: kotlin.Int? = 0,

    /* Grid Y position */
    @SerialName(value = "y") val y: kotlin.Int? = 0,

    /* Grid Width (cols) */
    @SerialName(value = "w") val w: kotlin.Int? = 6,

    /* Grid Height (rows) */
    @SerialName(value = "h") val h: kotlin.Int? = 4

) {


}

