/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Represents a single widget's new position.
 *
 * @param id 
 * @param order 
 * @param group 
 */
@Serializable

data class WidgetReorderItem (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "order") @Required val order: kotlin.Int,

    @SerialName(value = "group") val group: kotlin.String? = null

) {


}

