/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.healthplatform.pulsequery.api.models

import io.healthplatform.pulsequery.api.models.TextConfig

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Payload for creating a Text Widget. Strictly enforces `type=\"TEXT\"` and `config` matching TextConfig.
 *
 * @param title 
 * @param type 
 * @param config Text-specific configuration
 * @param visualization Fixed visualization ID for text.
 */
@Serializable

data class WidgetCreateText (

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "type") @Required val type: WidgetCreateText.Type,

    /* Text-specific configuration */
    @SerialName(value = "config") @Required val config: TextConfig,

    /* Fixed visualization ID for text. */
    @SerialName(value = "visualization") val visualization: WidgetCreateText.Visualization? = Visualization.markdown

) {

    /**
     * 
     *
     * Values: TEXT
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "TEXT") TEXT("TEXT");
    }
    /**
     * Fixed visualization ID for text.
     *
     * Values: markdown
     */
    @Serializable
    enum class Visualization(val value: kotlin.String) {
        @SerialName(value = "markdown") markdown("markdown");
    }

}

