name: KMP E2E Android (Maestro)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  maestro-android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build Android APK
        working-directory: ./PulseQuery
        run: ./gradlew :composeApp:assembleDebug

      - name: Install Maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Run Maestro Tests on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: default
          arch: x86_64
          profile: pixel_6
          script: |
            export PATH="$PATH":"$HOME/.maestro/bin"
            adb install ./PulseQuery/composeApp/build/outputs/apk/debug/composeApp-debug.apk
            maestro test ./PulseQuery/.maestro/
