"""feedback

Revision ID: 003
Revises: 002
Create Date: 2024-03-25 10:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "003"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """
  Apply migration: Create experiment_logs and model_candidates tables.

  This schema supports the Benchmarking Arena feature.
  1. experiment_logs: Tracks a distinct user question/prompt.
  2. model_candidates: Tracks the specific SQL generated by an LLM for that prompt,
     including whether it executed successfully and if the user chose it.
  """
  # 1. Create Experiment Logs Table
  op.create_table(
    "experiment_logs",
    sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("prompt_text", sa.Text(), nullable=False),
    sa.Column("prompt_strategy", sa.String(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_experiment_logs_user_id"), "experiment_logs", ["user_id"], unique=False)

  # 2. Create Model Candidates Table
  op.create_table(
    "model_candidates",
    sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("experiment_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("model_identifier", sa.String(), nullable=False),
    sa.Column("model_tag", sa.String(), nullable=False),
    sa.Column("generated_sql", sa.Text(), nullable=False),
    sa.Column("latency_ms", sa.Integer(), nullable=True),
    sa.Column("is_selected", sa.Boolean(), nullable=False),
    sa.Column("execution_success", sa.Boolean(), nullable=True),
    sa.Column("error_message", sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(["experiment_id"], ["experiment_logs.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_model_candidates_experiment_id"), "model_candidates", ["experiment_id"], unique=False)


def downgrade() -> None:
  """
  Revert migration: Drop feedback tracking tables.
  """
  op.drop_index(op.f("ix_model_candidates_experiment_id"), table_name="model_candidates")
  op.drop_table("model_candidates")
  op.drop_index(op.f("ix_experiment_logs_user_id"), table_name="experiment_logs")
  op.drop_table("experiment_logs")
