"""
Multi-provider LLM client for arena-style SQL generation.

Wraps any-llm providers, executes concurrent requests, and normalizes responses.
"""

import asyncio
import logging
import time
from collections.abc import AsyncGenerator
from typing import Any, Dict, List, NamedTuple, Optional

from any_llm import AnyLLM
from starlette.concurrency import run_in_threadpool

from app.core.config import settings
from app.schemas.admin import AdminSettingsResponse
from app.schemas.ai import ModelInfo

logger = logging.getLogger(__name__)


class FallbackMockProvider:
  """
  Synthetic fallback LLM provider utilized when no cloud API keys or local LLMs are active.

  Produces deterministic mock SQL analysis responses to preserve platform availability.

  Attributes:
      name (str): Human-readable provider identifier.
      model_name (str): Logical model tag.
  """

  def __init__(self, name: str = "System Mock", model_name: str = "mock-model") -> None:
    """
    Initializes the fallback mock provider.

    Args:
        name (str): Display name for the fallback provider.
        model_name (str): Internal model identifier.
    """
    self.name = name
    self.model_name = model_name

  def generate_response(self, messages: list[dict[str, str]]) -> str:
    """
    Generates a deterministic mock SQL query markdown codeblock.

    Args:
        messages (list[dict[str, str]]): Chat message conversation context.

    Returns:
        str: Formatted Markdown string containing synthetic fallback SQL query.
    """
    logger.warning("⚡ [FALLBACK MOCK] Generating synthetic fallback SQL response (No API key configured).")
    mock_sql = (
      "-- Generated by FallbackMockProvider (No API key configured)\n"
      "SELECT 'System Mock' as source, 'No LLM Configured' as status;"
    )
    return f"```sql\n{mock_sql}\n```"


class ArenaResponse(NamedTuple):
  """
  Standardized response object for a single model's contribution to the Arena.

  Attributes:
      provider_name (str): The display name of the model (e.g., "GPT-4o").
      model_identifier (str): The technical ID (e.g., "openai/gpt-4o").
      content (str): The raw text response (SQL).
      latency_ms (int): Time taken to generate in milliseconds.
      error (Optional[str]): Error message if generation failed.
      is_fallback (bool): Flag indicating if response originated from FallbackMockProvider.
  """

  provider_name: str
  model_identifier: str
  content: str
  latency_ms: int
  error: str | None = None
  is_fallback: bool = False


_DONE_SENTINEL = object()


def _extract_chunk_delta(chunk: Any) -> str | None:
  """
  Extracts text delta from a streaming completion chunk.

  Args:
      chunk (Any): Completion chunk object from any-llm provider.

  Returns:
      str | None: The extracted delta content string, or None if unavailable.
  """
  if hasattr(chunk, "choices") and chunk.choices:
    choice = chunk.choices[0]
    if hasattr(choice, "delta") and getattr(choice.delta, "content", None):
      return str(choice.delta.content)
    if getattr(choice, "text", None):
      return str(choice.text)
  return None


def _pump_stream_to_queue(
  stream_iterable: Any,
  queue: asyncio.Queue[Any],
  loop: asyncio.AbstractEventLoop,
) -> None:
  """
  Consumes a synchronous iterable in a background thread and queues tokens.

  Args:
      stream_iterable (Any): Synchronous generator or iterable producing chunks.
      queue (asyncio.Queue[Any]): Destination async queue for tokens or exceptions.
      loop (asyncio.AbstractEventLoop): The running asyncio event loop.
  """
  try:
    for chunk in stream_iterable:
      delta = _extract_chunk_delta(chunk)
      if delta:
        loop.call_soon_threadsafe(queue.put_nowait, delta)
    loop.call_soon_threadsafe(queue.put_nowait, _DONE_SENTINEL)
  except Exception as exc:
    loop.call_soon_threadsafe(queue.put_nowait, exc)


class LLMArenaClient:
  """
  A Multi-Provider LLM Client designed for benchmarking and fallback support.

  Instead of connecting to a single model, this client initializes a 'swarm' of
  clients based on configuration. It supports:
  1. Broadcasting a prompt to ALL models simultaneously (The Arena).
  2. Collecting performance metrics (Latency).
  3. Normalizing errors across different SDKs using `any-llm`.
  """

  def __init__(self, timeout: int = 60):
    """
    Initialize the Swarm based on settings.LLM_SWARM.

    Args:
        timeout (int): Global timeout for all providers.
    """
    self.timeout = timeout
    self.swarm: list[dict[str, Any]] = []
    self.init_swarm()

  def init_swarm(self, custom_api_keys: dict[str, str] | None = None) -> None:
    """
    Initializes or reloads the Swarm based on settings and updated API keys.

    Args:
        custom_api_keys (Optional[dict[str, str]]): Updated API keys to apply.
    """
    self.swarm = []
    keys = custom_api_keys or {}

    for config in settings.LLM_SWARM:
      try:
        # Initialize any-llm clients for each configured provider
        api_base = config.get("api_base") or config.get("base_url")
        provider = config["provider"]
        api_key = keys.get(provider) or keys.get(f"{provider.upper()}_API_KEY") or config.get("api_key")

        # NOTE: We do NOT pass 'model' here. OpenAI-compatible SDKs (v1+)
        # expect 'model' to be passed during the completion call, not client init.
        client = AnyLLM.create(
          provider,
          api_key=api_key,
          api_base=api_base,  # Only used for local/custom endpoints
          timeout=self.timeout,
        )

        self.swarm.append(
          {
            "client": client,
            "name": config["name"],  # Display Name
            "id": f"{config['provider']}/{config['model']}",  # Unique Tracking ID
            "model_name": config.get("model_name", config.get("model")),  # Actual Model ID
            "provider": config["provider"],
            "is_local": config.get("local", False),
          }
        )
        logger.info(f"Registered Arena Combatant: {config['name']} ({config['model']})")

      except Exception as e:
        logger.error(f"Failed to initialize LLM provider {config.get('name')}: {e}")

    # Fallback to prevent system crash if no providers are available
    if not self.swarm:
      logger.warning("Auto-configuring FallbackMockProvider (No valid LLMs found)")
      mock_provider = FallbackMockProvider()
      self.swarm.append(
        {
          "client": mock_provider,
          "name": mock_provider.name,
          "id": "mock/fallback",
          "model_name": mock_provider.model_name,
          "provider": "mock",
          "is_local": True,
        }
      )

  def reload_swarm(self, admin_settings: Any = None) -> None:
    """
    Reloads the swarm using updated API keys from admin configuration.

    Args:
        admin_settings (Any): The updated admin settings response containing api_keys.
    """
    api_keys = getattr(admin_settings, "api_keys", None) if admin_settings else None
    self.init_swarm(custom_api_keys=api_keys)

  def get_available_models(self, admin_settings: AdminSettingsResponse | None = None) -> list[ModelInfo]:
    """
    Returns a list of configured models. Filters by admin settings if provided.

    Args:
        admin_settings: Optional admin configuration to filter models by visibility.

    Returns:
        List of configured model information objects.
    """
    models = [
      ModelInfo(id=m["id"], name=m["name"], provider=m["provider"], is_local=m.get("is_local", False)) for m in self.swarm
    ]
    if admin_settings and admin_settings.visible_models:
      return [m for m in models if m.id in admin_settings.visible_models]
    return models

  async def _generate_single(
    self,
    combatant: dict[str, Any],
    messages: list[dict[str, str]],
    temperature: float,
    max_tokens: int,
    stop: list[str] | None,
    admin_settings: AdminSettingsResponse | None = None,
  ) -> ArenaResponse:
    """
    Internal wrapper to execute a request against a single provider
    and measure its latency.
    """
    client = combatant["client"]
    name = combatant["name"]
    model_id = combatant["id"]
    target_model_name = combatant["model_name"]

    start_time = time.time()

    # Handle Mock / Fallback Mode
    if isinstance(client, FallbackMockProvider) or client is None:
      provider_instance = (
        client
        if isinstance(client, FallbackMockProvider)
        else FallbackMockProvider(name=name, model_name=target_model_name)
      )
      content = provider_instance.generate_response(messages)
      return ArenaResponse(
        provider_name=name,
        model_identifier=model_id,
        content=content,
        latency_ms=10,
        error=None,
        is_fallback=True,
      )

    try:
      # Offload blocking IO to threadpool to keep asyncio loop healthy
      # We pass 'model' here to satisfy OpenAI SDK requirements
      kwargs = {}
      if admin_settings and admin_settings.api_keys:
        provider = combatant["provider"]
        if provider in admin_settings.api_keys:
          kwargs["api_key"] = admin_settings.api_keys[provider]

      response = await run_in_threadpool(
        client.completion,
        model=target_model_name,
        messages=messages,
        temperature=temperature,
        max_tokens=max_tokens,
        stop=stop,
        **kwargs,
      )

      # Measure Latency
      duration_ms = int((time.time() - start_time) * 1000)

      # Robust extraction of content
      try:
        content = response.choices[0].message.content.strip()
        return ArenaResponse(provider_name=name, model_identifier=model_id, content=content, latency_ms=duration_ms)
      except (AttributeError, IndexError):
        return ArenaResponse(
          provider_name=name,
          model_identifier=model_id,
          content="",
          latency_ms=duration_ms,
          error="Malformed response structure",
        )

    except Exception as e:
      duration_ms = int((time.time() - start_time) * 1000)
      return ArenaResponse(
        provider_name=name, model_identifier=model_id, content="", latency_ms=duration_ms, error=str(e)
      )

  async def generate_arena_competition(
    self,
    messages: list[dict[str, str]],
    temperature: float = 0.0,
    max_tokens: int = 512,
    stop: list[str] | None = None,
    target_model_ids: list[str] | None = None,
    admin_settings: AdminSettingsResponse | None = None,
  ) -> list[ArenaResponse]:
    """
    The Main Event: Broadcasts the prompt to all configured LLMs concurrently.
    Can be scoped to specific models via `target_model_ids`.

    Args:
        messages: OpenAI-format history.
        temperature: Determinism factor.
        max_tokens: Length limit.
        stop: Stop sequences (crucial for SQL generation).
        target_model_ids: Optional list of specific 'id's to query.

    Returns:
        List[ArenaResponse]: A list of results from every active model, including errors.
    """
    if not self.swarm:
      raise RuntimeError("No LLM providers are configured in the Arena.")

    # Filter combatants
    active_combatants = self.swarm
    if target_model_ids:
      active_combatants = [c for c in self.swarm if c["id"] in target_model_ids]

    if not active_combatants:
      # Fallback if filters didn't match anything -> Return empty or all?
      # Returning empty to signify strict adherence. Filters might be malformed.
      return []

    if not target_model_ids and admin_settings and admin_settings.visible_models:
      active_combatants = [c for c in active_combatants if c["id"] in admin_settings.visible_models]

    # Create tasks for all providers
    tasks = [
      self._generate_single(combatant, messages, temperature, max_tokens, stop, admin_settings)
      for combatant in active_combatants
    ]

    # Run all tasks concurrently
    results = await asyncio.gather(*tasks, return_exceptions=True)

    # Filter out unhandled coroutine exceptions (re-wrapping them as ArenaResponse errors)
    final_results = []
    for i, res in enumerate(results):
      if isinstance(res, ArenaResponse):
        final_results.append(res)
      else:
        # This catches Python crashes inside _generate_single
        combatant = active_combatants[i]
        final_results.append(
          ArenaResponse(
            provider_name=combatant["name"],
            model_identifier=combatant["id"],
            content="",
            latency_ms=0,
            error=f"Critical Client Error: {res!s}",
          )
        )

    return final_results

  async def stream_tokens(
    self,
    messages: list[dict[str, str]],
    model_id: str | None = None,
    temperature: float = 0.7,
    max_tokens: int = 1000,
    admin_settings: AdminSettingsResponse | None = None,
  ) -> AsyncGenerator[str, None]:
    """
    Streams tokens incrementally from the selected model (or first active model in the swarm).

    Args:
        messages: List of message dictionaries representing conversation history.
        model_id: Optional specific model identifier to target.
        temperature: Sampling temperature for generation.
        max_tokens: Maximum tokens to generate.
        admin_settings: Admin settings for API key and model visibility overrides.

    Yields:
        str: Incremental token strings.
    """
    if not self.swarm:
      yield "SELECT 'No LLM providers configured' as status;"
      return

    combatant = None
    if model_id:
      combatant = next((c for c in self.swarm if c["id"] == model_id), None)
    if not combatant:
      combatant = self.swarm[0]

    client = combatant.get("client")
    if isinstance(client, FallbackMockProvider) or client is None:
      mock_response = (
        "Here is the SQL query for your hospital data analysis:\n\n"
        "```sql\n"
        "SELECT Clinical_Service, COUNT(*) as patient_count\n"
        "FROM synthetic_hospital_data\n"
        "GROUP BY Clinical_Service\n"
        "ORDER BY patient_count DESC;\n"
        "```\n\n"
        "This query aggregates patient counts by clinical service."
      )
      words = mock_response.split(" ")
      for i, word in enumerate(words):
        token = word + (" " if i < len(words) - 1 else "")
        yield token
        await asyncio.sleep(0.01)
      return

    try:
      kwargs: dict[str, Any] = {}
      if admin_settings and admin_settings.api_keys:
        provider = combatant["provider"]
        if provider in admin_settings.api_keys:
          kwargs["api_key"] = admin_settings.api_keys[provider]

      target_model_name = combatant["model_name"]
      stream_result = await run_in_threadpool(
        client.completion,
        model=target_model_name,
        messages=messages,
        temperature=temperature,
        max_tokens=max_tokens,
        stream=True,
        **kwargs,
      )

      if hasattr(stream_result, "choices"):
        content = getattr(stream_result.choices[0].message, "content", "")
        for word in content.split(" "):
          yield word + " "
          await asyncio.sleep(0.01)
      elif hasattr(stream_result, "__aiter__"):
        async for chunk in stream_result:
          delta = _extract_chunk_delta(chunk)
          if delta:
            yield delta
            await asyncio.sleep(0.005)
      else:
        loop = asyncio.get_running_loop()
        queue: asyncio.Queue[Any] = asyncio.Queue()
        pump_task = asyncio.to_thread(_pump_stream_to_queue, stream_result, queue, loop)
        asyncio.create_task(pump_task)

        while True:
          item = await queue.get()
          if item is _DONE_SENTINEL:
            break
          if isinstance(item, Exception):
            raise item
          yield item
          await asyncio.sleep(0.005)

    except Exception as e:
      logger.warning(f"Streaming failed, falling back to standard generation: {e}")
      res = await self._generate_single(combatant, messages, temperature, max_tokens, None, admin_settings)
      if res.error:
        fallback_sql = (
          "Here is the fallback analysis query:\n\n"
          "```sql\n"
          "SELECT 'System Fallback' as source, 'synthetic_hospital_data' as dataset;\n"
          "```"
        )
        for word in fallback_sql.split(" "):
          yield word + " "
          await asyncio.sleep(0.005)
      else:
        for word in res.content.split(" "):
          yield word + " "
          await asyncio.sleep(0.01)


# Singleton instance
llm_client = LLMArenaClient()
