"""
Clinical PDF Report Generator for Hospital Shift Handovers and Dashboards.

Generates compliant PDF documents (PDF-1.4 standard) containing hospital metadata,
midnight census timestamps, widget table summaries, and author attribution
without requiring heavy external C-dependencies. Supports dynamic multi-page pagination.
"""

from datetime import UTC, datetime
from typing import Any


def _escape_pdf_text(text: str) -> str:
  """
  Escapes special characters in PDF string literals.

  Args:
      text (str): Input text string.

  Returns:
      str: Escaped string safe for PDF text objects.
  """
  cleaned = (
    text.replace(chr(92), chr(92) + chr(92)).replace(chr(40), chr(92) + chr(40)).replace(chr(41), chr(92) + chr(41))
  )
  return "".join(c if ord(c) < 128 else "?" for c in cleaned)


def _build_page_header(
  dashboard_name: str,
  author_email: str,
  formatted_time: str,
  page_index: int,
) -> tuple[list[str], int]:
  """
  Builds drawing commands for the page header and returns initial content y-coordinate.

  Args:
      dashboard_name (str): Title of the exported dashboard.
      author_email (str): Email of exporting user.
      formatted_time (str): Formatted census timestamp string.
      page_index (int): Zero-based index of current page.

  Returns:
      tuple[list[str], int]: List of PDF drawing commands and initial y_pos.
  """
  commands: list[str] = []
  if page_index == 0:
    escaped_title = _escape_pdf_text(f"Pulse Query Clinical Report: {dashboard_name}")
    commands.append(f"BT /F1 16 Tf 50 740 Td ({escaped_title}) Tj ET")

    escaped_author = _escape_pdf_text(f"Export Author: {author_email}")
    escaped_census = _escape_pdf_text(f"Midnight Census Timestamp: {formatted_time}")
    escaped_facility = _escape_pdf_text("Facility: Stanford Health Care - Clinical Analytics Operations")

    commands.append(f"BT /F1 10 Tf 50 715 Td ({escaped_facility}) Tj ET")
    commands.append(f"BT /F1 10 Tf 50 700 Td ({escaped_census}) Tj ET")
    commands.append(f"BT /F1 10 Tf 50 685 Td ({escaped_author}) Tj ET")
    commands.append("50 675 m 562 675 l S")
    return commands, 655
  else:
    escaped_title = _escape_pdf_text(f"Pulse Query Clinical Report: {dashboard_name} (Cont.)")
    commands.append(f"BT /F1 14 Tf 50 740 Td ({escaped_title}) Tj ET")
    escaped_census = _escape_pdf_text(f"Midnight Census: {formatted_time}")
    commands.append(f"BT /F1 9 Tf 50 720 Td ({escaped_census}) Tj ET")
    commands.append("50 710 m 562 710 l S")
    return commands, 690


def _build_page_footer(
  formatted_time: str,
  page_index: int,
  total_pages: int,
) -> list[str]:
  """
  Builds drawing commands for the standardized page footer.

  Args:
      formatted_time (str): Formatted timestamp.
      page_index (int): Zero-based page index.
      total_pages (int): Total page count.

  Returns:
      list[str]: PDF commands rendering footer line and pagination info.
  """
  commands: list[str] = ["50 50 m 562 50 l S"]
  escaped_footer = _escape_pdf_text(
    f"Generated by Pulse Query Engine | Page {page_index + 1} of {total_pages} | {formatted_time} | Confidential Clinical Data"
  )
  commands.append(f"BT /F1 8 Tf 50 38 Td ({escaped_footer}) Tj ET")
  return commands


def generate_clinical_pdf_report(
  dashboard_name: str,
  author_email: str,
  widgets_data: list[dict[str, Any]],
  census_timestamp: datetime | None = None,
) -> bytes:
  """
  Generates a multi-page clinical PDF report byte stream formatted for hospital shift handovers.

  Args:
      dashboard_name (str): Title of the exported dashboard.
      author_email (str): Email address of clinician or administrator exporting the report.
      widgets_data (list[dict[str, Any]]): List of widget data snapshots including titles, types, and rows.
      census_timestamp (datetime | None): Optional midnight census timestamp; defaults to current UTC time.

  Returns:
      bytes: Binary stream beginning with '%PDF-1.4' and ending with '%%EOF'.
  """
  if census_timestamp is None:
    census_timestamp = datetime.now(UTC)

  formatted_time = census_timestamp.strftime("%Y-%m-%d %H:%M:%S UTC")

  # Group widgets into pages based on coordinate height budgets
  pages_widget_groups: list[list[dict[str, Any]]] = []
  current_group: list[dict[str, Any]] = []
  current_y = 655

  for widget in widgets_data:
    # Estimate widget height in PDF points
    rows = widget.get("data", [])
    if isinstance(rows, list) and rows:
      w_height = 45
    else:
      w_height = 31

    if current_y - w_height < 80 and current_group:
      pages_widget_groups.append(current_group)
      current_group = [widget]
      current_y = 690 - w_height
    else:
      current_group.append(widget)
      current_y -= w_height

  if current_group:
    pages_widget_groups.append(current_group)
  else:
    pages_widget_groups.append([])

  total_pages = len(pages_widget_groups)
  page_streams: list[bytes] = []

  for p_idx, group in enumerate(pages_widget_groups):
    header_cmds, y_pos = _build_page_header(dashboard_name, author_email, formatted_time, p_idx)
    cmds = list(header_cmds)

    for widget in group:
      title = widget.get("title", "Untitled Widget")
      w_type = widget.get("type", "SQL")
      escaped_w_title = _escape_pdf_text(f"Widget: {title} [{w_type}]")
      cmds.append(f"BT /F1 11 Tf 50 {y_pos} Td ({escaped_w_title}) Tj ET")
      y_pos -= 15

      rows = widget.get("data", [])
      if isinstance(rows, list) and rows:
        first_row = rows[0]
        if isinstance(first_row, dict):
          col_names = list(first_row.keys())[:5]
          header_str = " | ".join(f"{k}: {first_row[k]}" for k in col_names)
          escaped_row = _escape_pdf_text(f"Sample: {header_str}")
          cmds.append(f"BT /F1 9 Tf 65 {y_pos} Td ({escaped_row}) Tj ET")
          y_pos -= 14
          escaped_summary = _escape_pdf_text(f"Total Records: {len(rows)}")
          cmds.append(f"BT /F1 9 Tf 65 {y_pos} Td ({escaped_summary}) Tj ET")
          y_pos -= 16
      elif widget.get("error"):
        escaped_err = _escape_pdf_text(f"Status: Error - {widget['error']}")
        cmds.append(f"BT /F1 9 Tf 65 {y_pos} Td ({escaped_err}) Tj ET")
        y_pos -= 16
      else:
        escaped_empty = _escape_pdf_text("Status: No data recorded.")
        cmds.append(f"BT /F1 9 Tf 65 {y_pos} Td ({escaped_empty}) Tj ET")
        y_pos -= 16

    footer_cmds = _build_page_footer(formatted_time, p_idx, total_pages)
    cmds.extend(footer_cmds)

    content_str = "\n".join(cmds) + "\n"
    page_streams.append(content_str.encode("latin1"))

  # Assemble Multi-Page PDF-1.4 Structure
  # Object IDs:
  # 1: Catalog
  # 2: Pages
  # 3: Font
  # For each page i (0 to N-1):
  #   Page obj ID: 4 + 2*i
  #   Contents obj ID: 5 + 2*i
  page_ids = [4 + 2 * i for i in range(total_pages)]
  kids_str = " ".join(f"{pid} 0 R" for pid in page_ids)

  objects: list[bytes] = [
    b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
    f"2 0 obj\n<< /Type /Pages /Kids [{kids_str}] /Count {total_pages} >>\nendobj\n".encode("latin1"),
    b"3 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
  ]

  for i in range(total_pages):
    page_id = 4 + 2 * i
    content_id = 5 + 2 * i
    p_bytes = page_streams[i]
    p_len = len(p_bytes)

    page_obj = (
      f"{page_id} 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
      f"/Contents {content_id} 0 R /Resources << /Font << /F1 3 0 R >> >> >>\nendobj\n".encode("latin1")
    )
    content_obj = (
      f"{content_id} 0 obj\n<< /Length {p_len} >>\nstream\n".encode("latin1") + p_bytes + b"\nendstream\nendobj\n"
    )
    objects.append(page_obj)
    objects.append(content_obj)

  header = b"%PDF-1.4\n"
  body = b""
  xref: list[int] = [0]
  offset = len(header)
  for obj in objects:
    xref.append(offset)
    body += obj
    offset += len(obj)

  xref_offset = offset
  xref_table = f"xref\n0 {len(xref)}\n0000000000 65535 f \n".encode("latin1")
  for off in xref[1:]:
    xref_table += f"{off:010d} 00000 n \n".encode("latin1")

  trailer = f"trailer\n<< /Size {len(xref)} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF\n".encode("latin1")

  return header + body + xref_table + trailer
