"""
Feedback Tracking Models.

This module defines the database entities required to benchmark Large Language Models (LLMs)
against clinical analytics questions. It tracks the Prompt (Experiment) and the
competing outcomes (Candidates).
"""

import uuid
from typing import List
from datetime import datetime
from sqlalchemy import String, Text, Boolean, Integer, DateTime, ForeignKey, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database.postgres import Base


class ExperimentLog(Base):
  """
  Represents a single "Arena" session where a user asked a question.

  Attributes:
      id (UUID): Unique identifier for the experiment.
      user_id (UUID): The user who initiated the request.
      prompt_text (str): The natural language question (e.g. "Show me ICU census").
      prompt_strategy (str): The engineering strategy used (e.g. "zero-shot", "rag-few-shot").
      created_at (datetime): Timestamp of the request.
      candidates (List[ModelCandidate]): The multiple SQL options generated by different LLMs.
  """

  __tablename__ = "experiment_logs"

  id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
  user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"), nullable=False)
  prompt_text: Mapped[str] = mapped_column(Text, nullable=False)
  prompt_strategy: Mapped[str] = mapped_column(String, nullable=True)
  created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)

  # Relationships
  candidates: Mapped[List["ModelCandidate"]] = relationship(
    "ModelCandidate", back_populates="experiment", cascade="all, delete-orphan", lazy="selectin"
  )


class ModelCandidate(Base):
  """
  Represents a specific LLM's attempt to answer the prompt.

  Attributes:
      id (UUID): Unique identifier for this candidate response.
      experiment_id (UUID): Link to the parent prompt.
      model_identifier (str): The specific backend model (e.g. "gemini-1.5-pro").
                              Internal use only; hidden from frontend to ensure blind testing.
      model_tag (str): The label displayed to the user (e.g. "Model A", "Option 1").
      generated_sql (str): The raw SQL code produced by the model.
      latency_ms (int): Time taken to generate the response in milliseconds.
      is_selected (bool): Feedback flag. True if the user clicked "Use This Query" or "Run".
      execution_success (bool): Telemetry flag. True if DuckDB executed the SQL without error.
      error_message (str): If execution failed, the error returned by DuckDB/SqlGlot.
  """

  __tablename__ = "model_candidates"

  id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
  experiment_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("experiment_logs.id"), nullable=False)

  model_identifier: Mapped[str] = mapped_column(String, nullable=False)
  model_tag: Mapped[str] = mapped_column(String, nullable=False)
  generated_sql: Mapped[str] = mapped_column(Text, nullable=False)
  latency_ms: Mapped[int] = mapped_column(Integer, nullable=True)

  # Feedback / Telemetry
  is_selected: Mapped[bool] = mapped_column(Boolean, default=False)
  execution_success: Mapped[bool] = mapped_column(Boolean, nullable=True)
  error_message: Mapped[str] = mapped_column(Text, nullable=True)

  # Relationships
  experiment: Mapped["ExperimentLog"] = relationship("ExperimentLog", back_populates="candidates")
